pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir -p public/dev public/qa
    - cp inpost-internship-assignments.html public/index.html
    - cp inpost-dev-intern-assignment.html public/dev/index.html
    - cp inpost-qa-intern-assignment.html public/qa/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
